language: ruby
rvm:
- 2.2

matrix:
  allowed_failure:
    - rvm: 2.2

before_install:
 - nvm install node

install:
 - npm install -g csslint
 - bundle install

before_script:
 - chmod +x ./script/cibuild

script:
 - ./script/cibuild
 - csslint _site/css/gallery.css
 - csslint _site/css/logo-nav.css
 - csslint _site/css/syntax.css

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
